/**
 * Indicator registry — names, default params, and output channel names.
 * The terminal UI uses this to drive the "Add indicator" picker and to
 * render parameter editors without hardcoding per-indicator forms.
 */

export type IndicatorInputType = 'int' | 'float' | 'enum' | 'bool';

export interface IndicatorInputSpec {
  key: string;
  label: string;
  type: IndicatorInputType;
  default: number | string | boolean;
  min?: number;
  max?: number;
  step?: number;
  options?: Array<{ label: string; value: string }>;
}

export type IndicatorPaneHint = 'overlay' | 'sub';

export interface IndicatorSpec {
  /** Stable identifier used everywhere; pass to the runner / UI. */
  type: string;
  label: string;
  /** Where the indicator naturally renders. */
  pane: IndicatorPaneHint;
  /** Output channels exposed to the signal language. */
  channels: string[];
  /** Inputs the user can tune. */
  inputs: IndicatorInputSpec[];
  /** Default style fields the UI lets the user override. */
  style: Record<string, string | number>;
  /** Optional short description used as a tooltip in the picker. */
  description?: string;
  /**
   * Search aliases / acronyms so the picker finds an indicator by its common short name
   * even when the display label spells it out (typing "ema" → Exponential Moving Average,
   * "bb" → Bollinger Bands). Populated from SEARCH_ALIASES below.
   */
  aliases?: string[];
}

export const INDICATOR_REGISTRY: IndicatorSpec[] = [
  {
    type: 'sma',
    label: 'Simple Moving Average',
    pane: 'overlay',
    channels: ['value'],
    inputs: [
      { key: 'length', label: 'Length', type: 'int', default: 20, min: 1, max: 500 },
      sourceInput(),
    ],
    style: { color: '#4caf50', lineWidth: 1.5 },
    description: 'Average of price over the lookback window.',
  },
  {
    type: 'ema',
    label: 'Exponential Moving Average',
    pane: 'overlay',
    channels: ['value'],
    inputs: [
      { key: 'length', label: 'Length', type: 'int', default: 21, min: 1, max: 500 },
      sourceInput(),
    ],
    style: { color: '#2196f3', lineWidth: 1.5 },
  },
  {
    type: 'wma',
    label: 'Weighted Moving Average',
    pane: 'overlay',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 20 }, sourceInput()],
    style: { color: '#9c27b0', lineWidth: 1.5 },
  },
  {
    type: 'hma',
    label: 'Hull Moving Average',
    pane: 'overlay',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 21 }, sourceInput()],
    style: { color: '#ff9800', lineWidth: 1.5 },
  },
  {
    type: 'dema',
    label: 'Double EMA',
    pane: 'overlay',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 21, min: 1 }, sourceInput()],
    style: { color: '#26c6da', lineWidth: 1.5 },
    description: 'Two cascaded EMAs minus their lag — faster than EMA.',
  },
  {
    type: 'tema',
    label: 'Triple EMA',
    pane: 'overlay',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 21, min: 1 }, sourceInput()],
    style: { color: '#66bb6a', lineWidth: 1.5 },
    description: 'Three cascaded EMAs — even less lag than DEMA.',
  },
  {
    type: 'vwma',
    label: 'Volume Weighted MA',
    pane: 'overlay',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 20, min: 1 }, sourceInput()],
    style: { color: '#ffa726', lineWidth: 1.5 },
    description: 'SMA weighted by each bar’s volume.',
  },
  {
    type: 'smma',
    label: 'Smoothed MA (RMA)',
    pane: 'overlay',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 21, min: 1 }, sourceInput()],
    style: { color: '#8d6e63', lineWidth: 1.5 },
    description: "Wilder's smoothed moving average — the basis of RSI/ATR.",
  },
  {
    type: 'alma',
    label: 'Arnaud Legoux MA',
    pane: 'overlay',
    channels: ['value'],
    inputs: [
      { key: 'length', label: 'Length', type: 'int', default: 21, min: 1 },
      { key: 'offset', label: 'Offset', type: 'float', default: 0.85, min: 0, max: 1, step: 0.05 },
      { key: 'sigma', label: 'Sigma', type: 'float', default: 6, min: 1, step: 0.5 },
      sourceInput(),
    ],
    style: { color: '#ab47bc', lineWidth: 1.5 },
    description: 'Gaussian-weighted MA — low lag with little overshoot.',
  },
  {
    type: 'lsma',
    label: 'Least Squares MA',
    pane: 'overlay',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 25, min: 1 }, sourceInput()],
    style: { color: '#42a5f5', lineWidth: 1.5 },
    description: 'Endpoint of a linear-regression line — a.k.a. linear regression curve.',
  },
  {
    type: 'kama',
    label: 'Kaufman Adaptive MA',
    pane: 'overlay',
    channels: ['value'],
    inputs: [
      { key: 'length', label: 'Length', type: 'int', default: 10, min: 1 },
      { key: 'fast', label: 'Fast', type: 'int', default: 2, min: 1 },
      { key: 'slow', label: 'Slow', type: 'int', default: 30, min: 1 },
      sourceInput(),
    ],
    style: { color: '#ec407a', lineWidth: 1.5 },
    description: 'Speeds up in trends, slows in chop via an efficiency ratio.',
  },
  {
    type: 't3',
    label: 'Tillson T3',
    pane: 'overlay',
    channels: ['value'],
    inputs: [
      { key: 'length', label: 'Length', type: 'int', default: 8, min: 1 },
      { key: 'vfactor', label: 'Volume Factor', type: 'float', default: 0.7, min: 0, max: 1, step: 0.1 },
      sourceInput(),
    ],
    style: { color: '#26a69a', lineWidth: 1.5 },
    description: 'Six-EMA smooth MA — very low lag, very smooth.',
  },
  {
    type: 'zlema',
    label: 'Zero-Lag EMA',
    pane: 'overlay',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 21, min: 1 }, sourceInput()],
    style: { color: '#7e57c2', lineWidth: 1.5 },
    description: 'EMA of a de-lagged price series — minimal lag.',
  },
  {
    type: 'mcginley',
    label: 'McGinley Dynamic',
    pane: 'overlay',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 14, min: 1 }, sourceInput()],
    style: { color: '#ffca28', lineWidth: 1.5 },
    description: 'Self-adjusting MA that hugs price through speed changes.',
  },
  {
    type: 'rsi',
    label: 'Relative Strength Index',
    pane: 'sub',
    channels: ['value'],
    inputs: [
      { key: 'length', label: 'Length', type: 'int', default: 14, min: 2 },
      sourceInput(),
    ],
    style: { color: '#ffb300', lineWidth: 1.5, upperBand: 70, lowerBand: 30 },
  },
  {
    type: 'macd',
    label: 'MACD',
    pane: 'sub',
    channels: ['macd', 'signal', 'histogram'],
    inputs: [
      { key: 'fast', label: 'Fast', type: 'int', default: 12 },
      { key: 'slow', label: 'Slow', type: 'int', default: 26 },
      { key: 'signal', label: 'Signal', type: 'int', default: 9 },
      sourceInput(),
    ],
    style: { macdColor: '#42a5f5', signalColor: '#ef5350', histogramPositive: '#26a69a', histogramNegative: '#ef5350' },
  },
  {
    type: 'stochastic',
    label: 'Stochastic',
    pane: 'sub',
    channels: ['k', 'd'],
    inputs: [
      { key: 'kLength', label: '%K Length', type: 'int', default: 14 },
      { key: 'kSmooth', label: '%K Smooth', type: 'int', default: 3 },
      { key: 'dSmooth', label: '%D Smooth', type: 'int', default: 3 },
    ],
    style: { kColor: '#42a5f5', dColor: '#ef5350', upperBand: 80, lowerBand: 20 },
  },
  {
    type: 'williams_r',
    label: 'Williams %R',
    pane: 'sub',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 14 }],
    style: { color: '#ab47bc', upperBand: -20, lowerBand: -80 },
  },
  {
    type: 'cci',
    label: 'CCI',
    pane: 'sub',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 20 }],
    style: { color: '#26a69a', upperBand: 100, lowerBand: -100 },
  },
  {
    type: 'mfi',
    label: 'Money Flow Index',
    pane: 'sub',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 14 }],
    style: { color: '#ffa726', upperBand: 80, lowerBand: 20 },
  },
  {
    type: 'roc',
    label: 'Rate of Change',
    pane: 'sub',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 9 }, sourceInput()],
    style: { color: '#7e57c2' },
  },
  {
    type: 'atr',
    label: 'Average True Range',
    pane: 'sub',
    channels: ['value'],
    inputs: [
      { key: 'length', label: 'Length', type: 'int', default: 14 },
      {
        key: 'smoothing',
        label: 'Smoothing',
        type: 'enum',
        default: 'rma',
        options: [
          { label: 'Wilder (RMA)', value: 'rma' },
          { label: 'EMA', value: 'ema' },
          { label: 'SMA', value: 'sma' },
        ],
      },
    ],
    style: { color: '#90a4ae' },
  },
  {
    type: 'bollinger',
    label: 'Bollinger Bands',
    pane: 'overlay',
    channels: ['middle', 'upper', 'lower', 'bandwidth', 'percentB'],
    inputs: [
      { key: 'length', label: 'Length', type: 'int', default: 20 },
      { key: 'multiplier', label: 'Multiplier', type: 'float', default: 2, step: 0.1 },
    ],
    style: { middleColor: '#cfd8dc', bandColor: '#90a4ae', fillOpacity: 0.08 },
  },
  {
    type: 'keltner',
    label: 'Keltner Channels',
    pane: 'overlay',
    channels: ['middle', 'upper', 'lower'],
    inputs: [
      { key: 'emaLength', label: 'EMA Length', type: 'int', default: 20 },
      { key: 'atrLength', label: 'ATR Length', type: 'int', default: 10 },
      { key: 'multiplier', label: 'Multiplier', type: 'float', default: 2, step: 0.1 },
    ],
    style: { middleColor: '#fff59d', bandColor: '#ffee58' },
  },
  {
    type: 'donchian',
    label: 'Donchian Channels',
    pane: 'overlay',
    channels: ['upper', 'lower', 'middle'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 20 }],
    style: { bandColor: '#80cbc4' },
  },
  {
    type: 'adx',
    label: 'ADX / DMI',
    pane: 'sub',
    channels: ['adx', 'plusDI', 'minusDI'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 14 }],
    style: { adxColor: '#ffffff', plusColor: '#26a69a', minusColor: '#ef5350' },
  },
  {
    type: 'supertrend',
    label: 'Supertrend',
    pane: 'overlay',
    channels: ['line', 'direction'],
    inputs: [
      { key: 'atrLength', label: 'ATR Length', type: 'int', default: 10 },
      { key: 'multiplier', label: 'Multiplier', type: 'float', default: 3, step: 0.1 },
    ],
    style: { upColor: '#26a69a', downColor: '#ef5350' },
  },
  {
    type: 'psar',
    label: 'Parabolic SAR',
    pane: 'overlay',
    channels: ['value'],
    inputs: [
      { key: 'start', label: 'Start', type: 'float', default: 0.02, step: 0.01 },
      { key: 'step', label: 'Step', type: 'float', default: 0.02, step: 0.01 },
      { key: 'max', label: 'Max', type: 'float', default: 0.2, step: 0.05 },
    ],
    style: { color: '#ec407a', dotSize: 3 },
  },
  {
    type: 'ichimoku',
    label: 'Ichimoku Cloud',
    pane: 'overlay',
    channels: ['conversion', 'base', 'spanA', 'spanB', 'lagging'],
    inputs: [
      { key: 'conversion', label: 'Conversion', type: 'int', default: 9 },
      { key: 'base', label: 'Base', type: 'int', default: 26 },
      { key: 'spanB', label: 'Span B', type: 'int', default: 52 },
      { key: 'displacement', label: 'Displacement', type: 'int', default: 26 },
    ],
    style: { conversionColor: '#42a5f5', baseColor: '#ef5350', cloudUp: '#26a69a40', cloudDown: '#ef535040' },
  },
  {
    type: 'aroon',
    label: 'Aroon',
    pane: 'sub',
    channels: ['up', 'down', 'oscillator'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 14 }],
    style: { upColor: '#26a69a', downColor: '#ef5350' },
  },
  {
    type: 'vwap',
    label: 'VWAP',
    pane: 'overlay',
    channels: ['value'],
    inputs: [
      {
        key: 'mode',
        label: 'Mode',
        type: 'enum',
        default: 'session',
        options: [
          { label: 'Session', value: 'session' },
          { label: 'Cumulative', value: 'cumulative' },
        ],
      },
    ],
    style: { color: '#ffa726', lineWidth: 1.5 },
  },
  {
    type: 'obv',
    label: 'On Balance Volume',
    pane: 'sub',
    channels: ['value'],
    inputs: [],
    style: { color: '#42a5f5' },
  },
  {
    type: 'cmf',
    label: 'Chaikin Money Flow',
    pane: 'sub',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 20 }],
    style: { color: '#ab47bc' },
  },
  {
    type: 'volume_oscillator',
    label: 'Volume Oscillator',
    pane: 'sub',
    channels: ['value'],
    inputs: [
      { key: 'shortLength', label: 'Short', type: 'int', default: 5 },
      { key: 'longLength', label: 'Long', type: 'int', default: 20 },
    ],
    style: { color: '#26a69a' },
  },
  {
    type: 'rvol',
    label: 'Relative Volume (RVOL)',
    pane: 'sub',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Lookback', type: 'int', default: 20, min: 2 }],
    style: { color: '#ffa726' },
    description:
      'Current bar volume ÷ average of the prior N bars. >1 = above-average participation. Works on every symbol (tick volume on FX).',
  },
  {
    type: 'vwap_bands',
    label: 'VWAP Bands (σ)',
    pane: 'overlay',
    channels: ['vwap', 'upper1', 'lower1', 'upper2', 'lower2'],
    inputs: [
      {
        key: 'mode',
        label: 'Mode',
        type: 'enum',
        default: 'session',
        options: [
          { label: 'Session', value: 'session' },
          { label: 'Cumulative', value: 'cumulative' },
        ],
      },
      { key: 'multiplier1', label: 'Inner σ', type: 'float', default: 1, step: 0.5, min: 0.5 },
      { key: 'multiplier2', label: 'Outer σ', type: 'float', default: 2, step: 0.5, min: 0.5 },
    ],
    style: { color: '#26c6da', bandColor: 'rgba(38,198,218,0.10)' },
    description:
      'Volume-weighted average price with ±σ standard-deviation bands. Session mode resets at the UTC day. Candle-derived — real on all symbols/timeframes.',
  },
  {
    type: 'initial_balance',
    label: 'Initial Balance',
    pane: 'overlay',
    channels: ['ibHigh', 'ibLow', 'ibMid'],
    inputs: [{ key: 'ibMinutes', label: 'IB minutes', type: 'int', default: 60, min: 5 }],
    style: { color: '#f06292', midColor: 'rgba(240,98,146,0.5)' },
    description:
      'High/low established in the first hour of each UTC session, drawn as flat reference levels. Intraday market-profile staple — real on all symbols.',
  },
  {
    type: 'naked_poc',
    label: 'Naked POC',
    pane: 'overlay',
    channels: ['poc'],
    inputs: [{ key: 'maxLevels', label: 'Max levels', type: 'int', default: 25, min: 1 }],
    style: { color: '#ffca28', filledColor: 'rgba(255,255,255,0.16)' },
    description:
      "Each completed session's volume Point of Control, drawn forward until price trades back through it. Untouched (virgin) POCs extend to now. Volume-profile POC on candle volume — real on all symbols.",
  },

  // ─── Momentum & community-favourite oscillators (sub-pane) ───
  {
    type: 'stoch_rsi',
    label: 'Stochastic RSI',
    pane: 'sub',
    channels: ['k', 'd'],
    inputs: [
      { key: 'rsiLength', label: 'RSI Length', type: 'int', default: 14, min: 2 },
      { key: 'stochLength', label: 'Stoch Length', type: 'int', default: 14, min: 1 },
      { key: 'kSmooth', label: '%K Smooth', type: 'int', default: 3, min: 1 },
      { key: 'dSmooth', label: '%D Smooth', type: 'int', default: 3, min: 1 },
    ],
    style: { kColor: '#42a5f5', dColor: '#ef5350', upperBand: 80, lowerBand: 20 },
    description: 'Stochastic applied to RSI — a faster, more sensitive overbought/oversold oscillator.',
  },
  {
    type: 'awesome',
    label: 'Awesome Oscillator',
    pane: 'sub',
    channels: ['histogram'],
    inputs: [
      { key: 'fast', label: 'Fast', type: 'int', default: 5, min: 1 },
      { key: 'slow', label: 'Slow', type: 'int', default: 34, min: 1 },
    ],
    style: { histogramPositive: '#26a69a', histogramNegative: '#ef5350' },
    description: 'SMA(median,5) − SMA(median,34). Bill Williams momentum histogram.',
  },
  {
    type: 'momentum',
    label: 'Momentum',
    pane: 'sub',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 10, min: 1 }, sourceInput()],
    style: { color: '#7e57c2' },
    description: 'Price minus the price N bars ago — raw momentum.',
  },
  {
    type: 'trix',
    label: 'TRIX',
    pane: 'sub',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 18, min: 1 }, sourceInput()],
    style: { color: '#26c6da', upperBand: 0 },
    description: 'Rate of change of a triple-smoothed EMA (basis points) — filters minor moves.',
  },
  {
    type: 'ultimate',
    label: 'Ultimate Oscillator',
    pane: 'sub',
    channels: ['value'],
    inputs: [
      { key: 'fast', label: 'Fast', type: 'int', default: 7, min: 1 },
      { key: 'mid', label: 'Mid', type: 'int', default: 14, min: 1 },
      { key: 'slow', label: 'Slow', type: 'int', default: 28, min: 1 },
    ],
    style: { color: '#ffa726', upperBand: 70, lowerBand: 30 },
    description: "Larry Williams' three-timeframe buying-pressure oscillator.",
  },
  {
    type: 'cmo',
    label: 'Chande Momentum Oscillator',
    pane: 'sub',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 9, min: 1 }, sourceInput()],
    style: { color: '#ab47bc', upperBand: 50, lowerBand: -50 },
    description: 'Pure momentum: (up−down)/(up+down) over the window, ±100.',
  },
  {
    type: 'dpo',
    label: 'Detrended Price Oscillator',
    pane: 'sub',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 21, min: 1 }, sourceInput()],
    style: { color: '#66bb6a', upperBand: 0 },
    description: 'Price minus a displaced SMA — strips the trend to expose cycles.',
  },
  {
    type: 'fisher',
    label: 'Fisher Transform',
    pane: 'sub',
    channels: ['fisher', 'trigger'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 9, min: 1 }],
    style: { fisherColor: '#42a5f5', triggerColor: '#ffa726', upperBand: 1.5, lowerBand: -1.5 },
    description: 'Gaussian-normalised price — sharp turning-point signals.',
  },
  {
    type: 'coppock',
    label: 'Coppock Curve',
    pane: 'sub',
    channels: ['value'],
    inputs: [
      { key: 'roc1', label: 'ROC 1', type: 'int', default: 14, min: 1 },
      { key: 'roc2', label: 'ROC 2', type: 'int', default: 11, min: 1 },
      { key: 'wma', label: 'WMA', type: 'int', default: 10, min: 1 },
    ],
    style: { color: '#26a69a', upperBand: 0 },
    description: 'WMA of summed long-term ROCs — long-cycle momentum.',
  },
  {
    type: 'kst',
    label: 'Know Sure Thing',
    pane: 'sub',
    channels: ['kst', 'signal'],
    inputs: [sourceInput()],
    style: { kstColor: '#42a5f5', signalColor: '#ef5350', upperBand: 0 },
    description: "Pring's weighted four-ROC momentum oscillator with a signal line.",
  },
  {
    type: 'tsi',
    label: 'True Strength Index',
    pane: 'sub',
    channels: ['tsi', 'signal'],
    inputs: [
      { key: 'long', label: 'Long', type: 'int', default: 25, min: 1 },
      { key: 'short', label: 'Short', type: 'int', default: 13, min: 1 },
      { key: 'signal', label: 'Signal', type: 'int', default: 13, min: 1 },
      sourceInput(),
    ],
    style: { tsiColor: '#42a5f5', signalColor: '#ffa726', upperBand: 25, lowerBand: -25 },
    description: 'Double-smoothed momentum ratio — trend + overbought/oversold.',
  },
  {
    type: 'rvgi',
    label: 'Relative Vigor Index',
    pane: 'sub',
    channels: ['rvgi', 'signal'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 10, min: 1 }],
    style: { rvgiColor: '#26a69a', signalColor: '#ef5350' },
    description: 'Close-vs-open vigor relative to the bar range, with a signal line.',
  },
  {
    type: 'bop',
    label: 'Balance of Power',
    pane: 'sub',
    channels: ['value'],
    inputs: [{ key: 'smooth', label: 'Smoothing', type: 'int', default: 14, min: 1 }],
    style: { color: '#7e57c2', upperBand: 0 },
    description: 'Where the close sits in the bar range — buyers vs sellers.',
  },
  {
    type: 'connors_rsi',
    label: 'Connors RSI',
    pane: 'sub',
    channels: ['value'],
    inputs: [
      { key: 'rsiLength', label: 'RSI', type: 'int', default: 3, min: 1 },
      { key: 'streakLength', label: 'Streak RSI', type: 'int', default: 2, min: 1 },
      { key: 'rankLength', label: 'Rank', type: 'int', default: 100, min: 2 },
    ],
    style: { color: '#ec407a', upperBand: 90, lowerBand: 10 },
    description: 'Composite of RSI, streak-RSI and percent-rank — mean-reversion timing.',
  },
  {
    type: 'smi',
    label: 'Stochastic Momentum Index',
    pane: 'sub',
    channels: ['smi', 'signal'],
    inputs: [
      { key: 'length', label: 'Length', type: 'int', default: 10, min: 1 },
      { key: 'smooth1', label: 'Smooth 1', type: 'int', default: 3, min: 1 },
      { key: 'smooth2', label: 'Smooth 2', type: 'int', default: 3, min: 1 },
      { key: 'signal', label: 'Signal', type: 'int', default: 3, min: 1 },
    ],
    style: { smiColor: '#42a5f5', signalColor: '#ffa726', upperBand: 40, lowerBand: -40 },
    description: 'Close vs the midpoint of the range, double-smoothed — refined stochastic.',
  },
  {
    type: 'wavetrend',
    label: 'WaveTrend Oscillator',
    pane: 'sub',
    channels: ['wt1', 'wt2'],
    inputs: [
      { key: 'channelLength', label: 'Channel', type: 'int', default: 10, min: 1 },
      { key: 'averageLength', label: 'Average', type: 'int', default: 21, min: 1 },
    ],
    style: { wt1Color: '#26c6da', wt2Color: '#ef5350', upperBand: 60, lowerBand: -60 },
    description: 'EMA-channel oscillator with a signal cross — momentum reversals.',
  },
  {
    type: 'squeeze_momentum',
    label: 'Squeeze Momentum',
    pane: 'sub',
    channels: ['histogram'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 20, min: 1 }],
    style: { histogramPositive: '#26a69a', histogramNegative: '#ef5350' },
    description: 'Linear-regression momentum (TTM concept) — Bollinger-in-Keltner squeeze release.',
  },
  {
    type: 'williams_vix_fix',
    label: 'Williams Vix Fix',
    pane: 'sub',
    channels: ['histogram'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 22, min: 2 }],
    style: { histogramPositive: '#26a69a', histogramNegative: '#26a69a' },
    description: "Synthetic VIX from the close range — spikes mark capitulation lows (Larry Williams).",
  },
  {
    type: 'choppiness',
    label: 'Choppiness Index',
    pane: 'sub',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 14, min: 2 }],
    style: { color: '#ffca28', upperBand: 61.8, lowerBand: 38.2 },
    description: 'Trend vs chop: >61.8 consolidating, <38.2 trending.',
  },
  {
    type: 'vortex',
    label: 'Vortex Indicator',
    pane: 'sub',
    channels: ['viPlus', 'viMinus'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 14, min: 1 }],
    style: { viPlusColor: '#26a69a', viMinusColor: '#ef5350' },
    description: 'VI+ / VI− directional trend lines — crosses flag trend changes.',
  },
  {
    type: 'mass_index',
    label: 'Mass Index',
    pane: 'sub',
    channels: ['value'],
    inputs: [
      { key: 'length', label: 'Sum', type: 'int', default: 25, min: 2 },
      { key: 'emaLength', label: 'EMA', type: 'int', default: 9, min: 1 },
    ],
    style: { color: '#ab47bc', upperBand: 27, lowerBand: 26.5 },
    description: 'Range-expansion gauge — a bulge above 27 warns of a reversal.',
  },
  {
    type: 'stc',
    label: 'Schaff Trend Cycle',
    pane: 'sub',
    channels: ['value'],
    inputs: [
      { key: 'fast', label: 'Fast', type: 'int', default: 23, min: 1 },
      { key: 'slow', label: 'Slow', type: 'int', default: 50, min: 1 },
      { key: 'cycle', label: 'Cycle', type: 'int', default: 10, min: 1 },
    ],
    style: { color: '#26c6da', upperBand: 75, lowerBand: 25 },
    description: 'Double-stochastic of MACD — a faster, cleaner trend-cycle signal.',
  },

  // ─── Volume & money flow (sub-pane) ───
  {
    type: 'adl',
    label: 'Accumulation / Distribution',
    pane: 'sub',
    channels: ['value'],
    inputs: [],
    style: { color: '#42a5f5' },
    description: 'Cumulative money-flow volume — accumulation vs distribution.',
  },
  {
    type: 'chaikin_osc',
    label: 'Chaikin Oscillator',
    pane: 'sub',
    channels: ['value'],
    inputs: [
      { key: 'fast', label: 'Fast', type: 'int', default: 3, min: 1 },
      { key: 'slow', label: 'Slow', type: 'int', default: 10, min: 1 },
    ],
    style: { color: '#ab47bc', upperBand: 0 },
    description: 'EMA(3)−EMA(10) of the A/D line — money-flow momentum.',
  },
  {
    type: 'eom',
    label: 'Ease of Movement',
    pane: 'sub',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 14, min: 1 }],
    style: { color: '#26a69a', upperBand: 0 },
    description: 'How easily price moves per unit volume — Arms EMV.',
  },
  {
    type: 'pvt',
    label: 'Price Volume Trend',
    pane: 'sub',
    channels: ['value'],
    inputs: [],
    style: { color: '#7e57c2' },
    description: 'Cumulative volume weighted by percent price change.',
  },
  {
    type: 'nvi',
    label: 'Negative Volume Index',
    pane: 'sub',
    channels: ['value'],
    inputs: [],
    style: { color: '#ef5350' },
    description: 'Tracks price on lower-volume days — the "smart money" proxy.',
  },
  {
    type: 'pvi',
    label: 'Positive Volume Index',
    pane: 'sub',
    channels: ['value'],
    inputs: [],
    style: { color: '#26a69a' },
    description: 'Tracks price on higher-volume days — the "crowd" proxy.',
  },
  {
    type: 'klinger',
    label: 'Klinger Volume Oscillator',
    pane: 'sub',
    channels: ['kvo', 'signal'],
    inputs: [
      { key: 'fast', label: 'Fast', type: 'int', default: 34, min: 1 },
      { key: 'slow', label: 'Slow', type: 'int', default: 55, min: 1 },
      { key: 'signal', label: 'Signal', type: 'int', default: 13, min: 1 },
    ],
    style: { kvoColor: '#42a5f5', signalColor: '#ffa726', upperBand: 0 },
    description: 'Long/short volume-force EMAs — money-flow trend + signal cross.',
  },
  {
    type: 'force_index',
    label: 'Elder Force Index',
    pane: 'sub',
    channels: ['value'],
    inputs: [{ key: 'length', label: 'Length', type: 'int', default: 13, min: 1 }],
    style: { color: '#26c6da', upperBand: 0 },
    description: 'Price change × volume, EMA-smoothed — conviction behind a move.',
  },
  {
    type: 'bull_bear_power',
    label: 'Elder Ray (Bull/Bear Power)',
    pane: 'sub',
    channels: ['bull', 'bear'],
    inputs: [{ key: 'length', label: 'EMA Length', type: 'int', default: 13, min: 1 }],
    style: { bullColor: '#26a69a', bearColor: '#ef5350', upperBand: 0 },
    description: 'High/low distance from an EMA — buying vs selling pressure.',
  },
  {
    type: 'net_volume',
    label: 'Net Volume',
    pane: 'sub',
    channels: ['histogram'],
    inputs: [],
    style: { histogramPositive: '#26a69a', histogramNegative: '#ef5350' },
    description: 'Per-bar volume signed by price direction.',
  },
];

/**
 * Searchable aliases / acronyms keyed by spec.type. The display labels spell names out
 * ("Exponential Moving Average"), so without these, typing the acronym a trader actually
 * uses ("ema", "bb", "sar") matched nothing. Universal short names only — no third-party
 * product identifiers. Applied to each spec below.
 */
const SEARCH_ALIASES: Record<string, string[]> = {
  sma: ['sma', 'ma'],
  ema: ['ema', 'ma'],
  wma: ['wma', 'ma'],
  hma: ['hma', 'ma'],
  dema: ['dema', 'ma'],
  tema: ['tema', 'ma'],
  vwma: ['vwma', 'ma'],
  smma: ['smma', 'rma', 'ma'],
  alma: ['alma', 'ma'],
  lsma: ['lsma', 'linreg', 'linear regression', 'ma'],
  kama: ['kama', 'ma'],
  t3: ['t3', 'tillson', 'ma'],
  zlema: ['zlema', 'zero lag', 'ma'],
  mcginley: ['mcginley', 'md', 'ma'],
  rsi: ['rsi'],
  macd: ['macd'],
  stochastic: ['stoch', 'stochastic', '%k', '%d'],
  williams_r: ['williams %r', 'wpr', 'willr', '%r'],
  cci: ['cci'],
  mfi: ['mfi'],
  roc: ['roc', 'momentum'],
  atr: ['atr'],
  bollinger: ['bb', 'bbands', 'boll'],
  keltner: ['kc'],
  donchian: ['dc'],
  adx: ['adx', 'dmi', 'di'],
  supertrend: ['st', 'supertrend'],
  psar: ['psar', 'sar'],
  ichimoku: ['ichimoku', 'cloud', 'kumo'],
  aroon: ['aroon'],
  vwap: ['vwap'],
  obv: ['obv'],
  cmf: ['cmf'],
  volume_oscillator: ['vo', 'volume osc'],
  rvol: ['rvol', 'relative volume'],
  vwap_bands: ['vwap bands', 'vwap σ', 'vwap std'],
  initial_balance: ['ib', 'initial balance'],
  naked_poc: ['npoc', 'poc', 'vpoc', 'naked poc'],
  stoch_rsi: ['stoch rsi', 'stochrsi', 'srsi'],
  awesome: ['ao', 'awesome'],
  momentum: ['mom', 'momentum'],
  trix: ['trix'],
  ultimate: ['uo', 'ultimate'],
  cmo: ['cmo', 'chande'],
  dpo: ['dpo', 'detrended'],
  fisher: ['fisher', 'fish'],
  coppock: ['coppock'],
  kst: ['kst', 'know sure thing'],
  tsi: ['tsi', 'true strength'],
  rvgi: ['rvgi', 'rvi', 'vigor'],
  bop: ['bop', 'balance of power'],
  connors_rsi: ['crsi', 'connors'],
  smi: ['smi', 'stochastic momentum'],
  wavetrend: ['wt', 'wavetrend'],
  squeeze_momentum: ['squeeze', 'sqzmom', 'ttm'],
  williams_vix_fix: ['wvf', 'vix fix', 'cm'],
  choppiness: ['chop', 'choppiness'],
  vortex: ['vi', 'vortex'],
  mass_index: ['mass index', 'mi'],
  stc: ['stc', 'schaff'],
  adl: ['adl', 'a/d', 'accumulation distribution', 'accum'],
  chaikin_osc: ['chaikin', 'cho'],
  eom: ['eom', 'emv', 'ease of movement'],
  pvt: ['pvt', 'price volume trend'],
  nvi: ['nvi', 'negative volume'],
  pvi: ['pvi', 'positive volume'],
  klinger: ['kvo', 'klinger'],
  force_index: ['force index', 'efi', 'elder force'],
  bull_bear_power: ['elder ray', 'bull bear power', 'bbp'],
  net_volume: ['net volume', 'netvol'],
};

for (const s of INDICATOR_REGISTRY) {
  if (!s.aliases) s.aliases = SEARCH_ALIASES[s.type];
}

export const INDICATOR_LOOKUP: Record<string, IndicatorSpec> = Object.fromEntries(
  INDICATOR_REGISTRY.map((s) => [s.type, s]),
);

function sourceInput(): IndicatorInputSpec {
  return {
    key: 'source',
    label: 'Source',
    type: 'enum',
    default: 'close',
    options: [
      { label: 'Open', value: 'open' },
      { label: 'High', value: 'high' },
      { label: 'Low', value: 'low' },
      { label: 'Close', value: 'close' },
      { label: 'HL2', value: 'hl2' },
      { label: 'HLC3', value: 'hlc3' },
      { label: 'OHLC4', value: 'ohlc4' },
    ],
  };
}
